version: '3'

services:
  database:
    container_name: portfolio_db
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    container_name: portfolio_main
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000 && python3 portfolio/worker.py"
    environment: 
      - "PYTHONUNBUFFERED=1"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - database

  redis:
    restart: always
    container_name: porfolio_redis_server
    image: redis:5.0.3
    ports:
      - "6379:6379"

volumes:
  postgres_data: