version: '3'

services:
  database:
    container_name: portfolio_db
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    container_name: portfolio_main
    command: python3 manage.py runserver 0.0.0.0:8000
    environment: 
      - "PYTHONUNBUFFERED=1"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - database
  
  tasks:
    build: .
    restart: always
    container_name: portfolio_django_background_tasks
    command: bash -c "chmod 755 process_tasks.sh && ./process_tasks.sh"
    environment: 
      - "PYTHONUNBUFFERED=1"
    volumes:
      - .:/src
    depends_on:
      - web
      - database 

volumes:
  postgres_data: