# Generated by Django 2.2.2 on 2019-08-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_analytics', models.CharField(choices=[('G', 'GitHub'), ('L', 'LinkedIn'), ('I', 'Instagram')], max_length=50)),
                ('headers_information', models.TextField(max_length=2000, null=True)),
                ('date_clicked', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytic',
                'verbose_name_plural': 'Analytics',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=450)),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.CharField(max_length=150)),
                ('about', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Page Data',
                'verbose_name_plural': 'Page Data',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('image_url', models.CharField(max_length=150)),
                ('project_url', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
