# Generated by Django 2.2.2 on 2019-09-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='date_clicked',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='analytics',
            old_name='headers_information',
            new_name='headers',
        ),
        migrations.RenameField(
            model_name='analytics',
            old_name='type_of_analytics',
            new_name='type',
        ),
    ]
