# Generated by Django 2.2.2 on 2019-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=50)),
                ('project_url', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
