# Generated by Django 2.2.2 on 2019-08-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_analytics', models.CharField(choices=[('G', 'Github'), ('L', 'Linkedin'), ('I', 'Instagram')], max_length=1)),
                ('date_clicked', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
            },
        ),
    ]
