# Generated by Django 2.2.2 on 2019-08-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20190808_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Projects', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=450),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_url',
            field=models.CharField(max_length=150),
        ),
    ]
