# Generated by Django 2.2.2 on 2019-08-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='analytics',
            options={'verbose_name': 'Analytic', 'verbose_name_plural': 'Analytics'},
        ),
        migrations.AlterField(
            model_name='analytics',
            name='type_of_analytics',
            field=models.CharField(choices=[('G', 'GitHub'), ('L', 'LinkedIn'), ('I', 'Instagram')], max_length=50),
        ),
    ]
