# Generated by Django 2.2.2 on 2019-08-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20190814_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=1000)),
                ('profile_url', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'PageData',
                'verbose_name_plural': 'PageData',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
