# Generated by Django 2.2.2 on 2019-08-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20190814_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagedata',
            options={'verbose_name': 'Page Data', 'verbose_name_plural': 'Page Data'},
        ),
    ]
