# Generated by Django 2.2.2 on 2019-08-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_projects_tech_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tech_stack',
        ),
    ]
