# Generated by Django 2.2.2 on 2019-08-17 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_remove_projects_tech_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='full_name',
            new_name='name',
        ),
    ]
