# Generated by Django 2.2.2 on 2019-08-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_auto_20190816_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='headers_information',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
