# Generated by Django 2.2.2 on 2019-08-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_analytics_headers_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='headers_information',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
