# Generated by Django 2.2.2 on 2019-08-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20190816_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='headers_information',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
